# Generated by Django 2.2.6 on 2019-10-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=300, verbose_name='Correo electrónico')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Imagen referencial')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name_category', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo Electrónico')),
                ('issue', models.CharField(max_length=100, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('reference_image', models.ImageField(max_length=255, upload_to='imagenes/', verbose_name='Imagen Referencial')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('is_public', models.BooleanField(default=False, verbose_name='Publicado / No Publicado')),
                ('relevant', models.BooleanField(default=False, verbose_name='Relevante / No relevante')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('delete_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('file', models.FileField(max_length='255', upload_to='documents/', verbose_name='Documento referencial')),
                ('level', models.CharField(choices=[('KINDER', 'Kinder'), ('PRIMERO', '1ero Básico'), ('SEGUNDO', '2do Básico'), ('TERCERO', '3ero Básico'), ('CUARTO', '4to Básico'), ('QUINTO', '5to Básico'), ('SEXTO', '6to Básico'), ('SEPTIMO', '7mo Básico'), ('OCTAVO', '8vo Básico'), ('PRIMERO_MEDIO', '1ero Medio'), ('SEGUNDO_MEDIO', '2do Medio'), ('TERCERO_MEDIO', '3ero Medio'), ('CUARTO_MEDIO', '4to Médio')], max_length=12)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('is_public', models.BooleanField(default=False, verbose_name='Publicado / No Publicado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Author')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
