# Generated by Django 2.2.6 on 2019-11-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191019_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='documentPicture/', verbose_name='Imagen referencial'),
        ),
    ]
