# Generated by Django 3.0.2 on 2020-01-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_document_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reference_url',
            field=models.URLField(default=True, max_length=300, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
